"use client";

import { useState } from "react";
import { product } from "./product";

const moments = [
  { stage: "3-2", title: "Building a reserve", label: "Economy", gold: "30 → 50", shops: "6", paths: "1", observation: "Your gold reserve grew across the selected Stage 3 snapshots while your core board remained stable.", reflection: "Preserving that reserve gave you more room to explore a later transition. Review the tradeoff between immediate board strength and future flexibility, rather than judging the decision by placement alone.", evidence: "Synthetic timeline: 30g at 3-2, 40g at 3-3 and 50g at 3-5. These are snapshots, not a complete transaction ledger.", goal: "Name the tradeoff before spending my reserve." },
  { stage: "4-1", title: "The transition window", label: "Transition", gold: "42 → 8", shops: "17", paths: "2", observation: "During the 4-1 window, the example player spent 34 gold net and encountered 17 shops. Two potential transition paths appeared among those shops.", reflection: "You committed to one line early. Revisit the other path and compare what it required from your board, items and remaining gold. It is a possibility to discuss, not a guarantee of a better finish.", evidence: "Synthetic evidence: selected balance snapshots of 42g, 38g, 31g, 24g, 18g and 8g. Net spend includes the whole transition window; it is not presented as reroll cost alone. Unit and item identities are deliberately abstracted in this concept.", goal: "Consider two transition paths before committing." },
  { stage: "5-1", title: "Keeping a coherent board", label: "Itemization", gold: "18 → 28", shops: "4", paths: "1", observation: "In this example, completed items supported the board direction selected in Stage 4, while the gold reserve began to recover.", reflection: "That consistency is a strength. In your review, separate the quality of the plan from the result of a single fight. Discuss which item decisions supported the plan and where the evidence is incomplete.", evidence: "Synthetic summary: two completed items assigned to the chosen carry role, and reserve snapshots of 18g and 28g. No opponent composition or current augment data is part of this example.", goal: "Explain how my item choices support my board plan." },
];

export function ReviewDemo() {
  const [selected, setSelected] = useState(1);
  const [saved, setSaved] = useState<string | null>(null);
  const moment = moments[selected];
  return <div className="reviewApp">
    <div className="appBar"><div><span className="miniBrand">T·</span><strong>{product.name}</strong><span className="appBarDivider">/</span><span>Match review</span></div><span className="pill">SYNTHETIC DEMO</span></div>
    <div className="appBody"><aside className="reviewSidebar"><small>COMPLETED MATCH</small><h3>One game.<br />Three moments.</h3><p>4th place <span>·</span> 34:18</p><div className="momentList" aria-label="Review moments">{moments.map((m,i)=><button key={m.stage} aria-pressed={selected === i} onClick={()=>setSelected(i)}><span>{m.stage}</span><div><b>{m.label}</b><small>{m.title}</small></div><span aria-hidden="true">↗</span></button>)}</div><div className="sidebarNote"><span className="statusDot" /> Analysis unlocked<p>The full match has ended.</p></div></aside>
    <div className="reviewContent"><div className="reviewTitle"><div><small>DECISION REVIEW / STAGE {moment.stage}</small><h3>{moment.title}</h3></div><span className="reviewCount">0{selected + 1} / 03</span></div><div className="statsRow"><div><small>GOLD SNAPSHOTS</small><b>{moment.gold}<span> g</span></b></div><div><small>SHOPS ENCOUNTERED</small><b>{moment.shops}</b></div><div><small>POTENTIAL PATHS</small><b>{moment.paths}</b></div></div>
    <div className="reviewNarrative" key={selected}><div><span className="findingTag goldText">WHAT THE TIMELINE SHOWS</span><p>{moment.observation}</p></div><div className="explanation"><span className="coachIcon" aria-hidden="true">✧</span><div><span className="findingTag mintText">ILLUSTRATIVE COACH EXPLANATION</span><p>{moment.reflection}</p></div></div><details className="evidence"><summary>Inspect supporting evidence <span aria-hidden="true">＋</span></summary><p>{moment.evidence}</p><p>All figures and explanations are authored sample content, not generated analysis. A production coach would identify missing evidence and avoid inventing unseen choices.</p></details></div>
    <div className="practiceGoal"><div><small>FUTURE PRACTICE OBJECTIVE</small><p>{moment.goal}</p></div><button className="button primary" onClick={()=>setSaved(moment.goal)}>{saved === moment.goal ? "Goal saved ✓" : "Save practice goal"}</button></div><p role="status" className="demoStatus">{saved ? `Demo goal: “${saved}” Saved only for this page session; it does not react to live gameplay.` : "Select a moment to explore. Saved goals are demo state only and reset on reload."}</p>
    </div></div>
  </div>;
}

export function OverlayDemo() {
  const [visible,setVisible]=useState(true);
  const [reference,setReference]=useState(false);
  return <div className="overlayContainer">{visible ? <div className="overlayMock"><div className="overlayHeader"><span className="miniBrand">T·</span><strong>{product.name}</strong><span>STATIC</span><button aria-label="Dismiss demo overlay" onClick={()=>setVisible(false)}>×</button></div><div className="overlayBody"><small>FOCUS SET BEFORE THIS MATCH</small><p>Consider two transition paths.</p><span>From your previous coaching session.<br />Unchanged throughout this match.</span><button className="referenceButton" aria-expanded={reference} onClick={()=>setReference(!reference)}>Static reference example <span aria-hidden="true">{reference ? "−" : "+"}</span></button>{reference && <div className="referencePanel"><strong>Item reference</strong><p>The proposed library contains fixed item descriptions and component recipes, available before the match. It never filters or ranks them using your current board or inventory.</p><small>Concept panel · no game data connected</small></div>}</div></div> : <div className="dismissedOverlay"><p>Overlay dismissed.</p><button className="button secondary" onClick={()=>setVisible(true)}>Show demo overlay</button></div>}</div>;
}

export function PrivacyDemo() {
  const [recording,setRecording]=useState(false);
  const [screenshots,setScreenshots]=useState(false);
  const [matches,setMatches]=useState(2);
  const [message,setMessage]=useState("Demo settings reset when you reload the page.");
  return <div className="privacyControls"><div className="controlsHeader"><strong>Recording preferences</strong><span className="pill">DEMO ONLY</span></div><div className="controlRow"><div><b>Match recording</b><p>Proposed opt-in collection of approved events</p></div><button className="switch" role="switch" aria-checked={recording} aria-label="Demo match recording" onClick={()=>{setRecording(!recording); if(recording) setScreenshots(false); setMessage("Demo preference changed. No gameplay is being recorded.");}}><span /></button></div><div className="controlRow"><div><b>Own-board screenshots</b><p>Optional · off by default · separate approval</p></div><button className="switch" role="switch" aria-checked={screenshots} aria-label="Demo own-board screenshots" disabled={!recording} onClick={()=>{setScreenshots(!screenshots);setMessage("Demo preference changed. No screenshots are captured.");}}><span /></button></div><div className="historyRow"><div><b>Sample coaching history</b><p>{matches} synthetic {matches === 1 ? "match" : "matches"}</p></div><div><button disabled={!matches} onClick={()=>{setMatches(matches-1);setMessage("Removed one synthetic match from the controls demo. The sample report above remains available.");}}>Delete one</button><button disabled={!matches} onClick={()=>{setMatches(0);setMessage("Cleared synthetic history from the controls demo. No real data was deleted.");}}>Delete all</button></div></div><p role="status" className="demoStatus">{message}</p><p className="retentionNote">Planned controls include deletion of matches, reports and captures. Production retention periods, storage location and any AI processor will be disclosed before real collection begins.</p></div>;
}
